import React from "react";
import { FileText, AlertTriangle, CheckCircle } from "lucide-react";

export const metadata = {
  title: "Terms of Service – SmartSprout",
  description: "Terms of service for SmartSprout kids learning platform.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-sky-light/20 via-white to-white">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {/* Header */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-sky-light/40 text-sky-deep text-sm font-heading font-bold mb-4">
            <FileText className="w-4 h-4" />
            Legal
          </div>
          <h1 className="text-4xl font-heading font-black text-gray-900 mb-3">
            Terms of Service
          </h1>
          <p className="text-gray-500">Last updated: August 2026</p>
        </div>

        <div className="card-playful prose prose-gray max-w-none space-y-8">
          <section>
            <h2 className="text-xl font-heading font-bold text-gray-800">1. Acceptance of Terms</h2>
            <p className="text-gray-600 leading-relaxed">
              By accessing and using SmartSprout (&ldquo;the Service&rdquo;), you agree to be bound by these
              Terms of Service. If you do not agree to these terms, please do not use the Service.
              If you are a parent or guardian, you are responsible for your child&apos;s use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-heading font-bold text-gray-800">2. Description of Service</h2>
            <p className="text-gray-600 leading-relaxed">
              SmartSprout provides free AI-powered educational tools for children ages 3-10, including:
            </p>
            <ul className="space-y-1 text-gray-600">
              <li className="flex items-start gap-2">
                <CheckCircle className="w-4 h-4 text-sprout-500 mt-1 flex-shrink-0" />
                AI Story Generator for personalized bedtime stories
              </li>
              <li className="flex items-start gap-2">
                <CheckCircle className="w-4 h-4 text-sprout-500 mt-1 flex-shrink-0" />
                Printable Worksheet Generator for math and English practice
              </li>
              <li className="flex items-start gap-2">
                <CheckCircle className="w-4 h-4 text-sprout-500 mt-1 flex-shrink-0" />
                AI Coloring Page Generator with printable outlines
              </li>
              <li className="flex items-start gap-2">
                <CheckCircle className="w-4 h-4 text-sprout-500 mt-1 flex-shrink-0" />
                Screen-Free Activity Finder for crafts and experiments
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-heading font-bold text-gray-800">3. User Conduct</h2>
            <p className="text-gray-600 leading-relaxed">
              Users agree to use the Service only for lawful purposes. You may not:
            </p>
            <ul className="space-y-1 text-gray-600 text-sm">
              <li>• Attempt to generate inappropriate or harmful content</li>
              <li>• Use automated systems to overwhelm our servers</li>
              <li>• Modify, reverse-engineer, or redistribute the Service</li>
              <li>• Use the Service for any commercial purpose without permission</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-heading font-bold text-gray-800">4. AI-Generated Content</h2>
            <div className="bg-amber-50 border border-amber-200 rounded-2xl p-4">
              <div className="flex items-center gap-2 text-amber-700 font-heading font-bold mb-2">
                <AlertTriangle className="w-4 h-4" />
                Important Notice
              </div>
              <p className="text-amber-700 text-sm leading-relaxed">
                Content generated by our AI tools is created algorithmically and may occasionally
                contain inaccuracies. While we implement strict safety filters for child-appropriate
                content, parents and guardians should review generated materials. SmartSprout does
                not guarantee the educational accuracy of AI-generated content.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-heading font-bold text-gray-800">5. Intellectual Property</h2>
            <p className="text-gray-600 leading-relaxed">
              Content you generate using SmartSprout (stories, worksheets, coloring pages, activities)
              is yours for personal, non-commercial use. The SmartSprout brand, logo, and platform
              design are our intellectual property.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-heading font-bold text-gray-800">6. Disclaimer of Warranties</h2>
            <p className="text-gray-600 leading-relaxed">
              The Service is provided &ldquo;as is&rdquo; without warranties of any kind. We do not warrant
              that the Service will be uninterrupted, error-free, or free of harmful components.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-heading font-bold text-gray-800">7. Limitation of Liability</h2>
            <p className="text-gray-600 leading-relaxed">
              SmartSprout shall not be liable for any indirect, incidental, special, or consequential
              damages arising from the use of our Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-heading font-bold text-gray-800">8. Changes to Terms</h2>
            <p className="text-gray-600 leading-relaxed">
              We reserve the right to modify these terms at any time. Continued use of the Service
              after changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-heading font-bold text-gray-800">9. Contact</h2>
            <p className="text-gray-600 leading-relaxed">
              For questions about these terms, contact us at: <strong>arvaancorelogic@gmail.com</strong>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
